"""
Locator Loader Utility

Loads locators from YAML files and provides them to Page Objects.
"""
import yaml
from pathlib import Path
from typing import Optional


class LocatorLoader:
    """Loads and provides access to locators from YAML files."""

    _cache: dict = {}
    _synced_cache: dict = {}  # Cache for new synced format

    @classmethod
    def load(cls, yaml_path: str) -> dict:
        """
        Load locators from a YAML file.

        Args:
            yaml_path: Path to the YAML file (relative to tests/locators or absolute)

        Returns:
            Dictionary containing all locators from the file
        """
        # Check cache first
        if yaml_path in cls._cache:
            return cls._cache[yaml_path]

        # Resolve path
        path = Path(yaml_path)
        if not path.is_absolute():
            # Try relative to tests/locators
            base_path = Path(__file__).parent.parent / "locators"
            path = base_path / yaml_path

        if not path.exists():
            raise FileNotFoundError(f"Locator file not found: {path}")

        with open(path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)

        cls._cache[yaml_path] = data
        return data

    @classmethod
    def get_locator(cls, yaml_path: str, category: str, identifier: str,
                    identifier_field: str = "aria_label") -> Optional[str]:
        """
        Get a specific locator string from the YAML file.

        Args:
            yaml_path: Path to the YAML file
            category: Category (buttons, inputs, headings, etc.)
            identifier: Value to match (e.g., "Send message" for aria_label)
            identifier_field: Field to match against (aria_label, placeholder, title, text)

        Returns:
            The recommended locator string or None if not found
        """
        data = cls.load(yaml_path)
        elements = data.get(category, [])

        for elem in elements:
            if elem.get(identifier_field) == identifier:
                return elem.get("recommended")

        return None

    @classmethod
    def get_all_by_category(cls, yaml_path: str, category: str) -> list:
        """
        Get all locators for a category.

        Args:
            yaml_path: Path to the YAML file
            category: Category (buttons, inputs, headings, etc.)

        Returns:
            List of element dictionaries
        """
        data = cls.load(yaml_path)
        return data.get(category, [])

    @classmethod
    def clear_cache(cls):
        """Clear the locator cache."""
        cls._cache.clear()
        cls._synced_cache.clear()

    @classmethod
    def get_synced_locator(cls, yaml_path: str, locator_key: str) -> Optional[str]:
        """
        Get a locator from the new synced YAML format (generated by sync-locators.ts).

        Args:
            yaml_path: Path to the YAML file
            locator_key: Key in the locators dict (e.g., 'aqa_welcome_message')

        Returns:
            The testid string or None if not found
        """
        data = cls.load(yaml_path)
        locators = data.get('locators', {})
        entry = locators.get(locator_key)
        if entry:
            return entry.get('testid')
        return None

    @classmethod
    def get_all_synced_locators(cls, yaml_path: str) -> dict:
        """
        Get all locators from the new synced YAML format.

        Args:
            yaml_path: Path to the YAML file

        Returns:
            Dictionary of locator_key -> testid
        """
        data = cls.load(yaml_path)
        locators = data.get('locators', {})
        return {key: entry.get('testid') for key, entry in locators.items() if entry}